"""Sanad parent store (ST-16, first half).

Persists the PARENTS that `chunking.py` produces, as the JSON files
architecture section 7.5 specifies: one file per parent at
`<parent_store_path>/<workspace_id>/<parent_id>.json`, holding the
parent's full text plus `source_file` and `section_label`.

Why parents live on disk as files and not in SQLite (ADR-08): they are
big text blobs, they are written once and read whole, and keeping them
out of the registry keeps the database small and fast for the queries it
actually serves. The vector store holds only the small child chunks and
carries `parent_id` in its payload; at answer time a search hit is traded
for the full section by reading exactly one file. Search the small thing,
read the big thing.

This module STORES and RETRIEVES. It embeds nothing and searches nothing:
the Qdrant side of ST-16 is the other half, and it is the half that has
to wait for ST-15's handover shape. This half depends only on ST-14's
`Parent`, which is merged and stable, so it can be finished first.

`Parent` is imported from chunking.py rather than redefined. A second
parent shape in a second module is how the two silently drift apart until
a field means different things on either side of a save.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path

from chunking import Parent
from config import get_settings

# Identifiers become path segments, so they are checked against this before
# ever touching the filesystem. Deliberately a strict allow-list rather than
# a "reject .." blocklist: blocklists lose to encodings, alternate
# separators and the next trick nobody thought of, whereas nothing outside
# this set can traverse anywhere no matter how it is spelled.
_SAFE_IDENTIFIER = re.compile(r"^[A-Za-z0-9_-]+$")

# Written and read back to prove a file is the parent its NAME claims.
_FIELD_ID = "id"
_FIELD_TEXT = "text"
_FIELD_SOURCE_FILE = "source_file"
_FIELD_SECTION_LABEL = "section_label"

# Suffix for the half-written file that `os.replace` swaps into place.
_TEMP_SUFFIX = ".tmp"

_JSON_SUFFIX = ".json"


class ParentStoreError(Exception):
    """Base class for parent-store errors, so callers catch this instead of
    OSError and json.JSONDecodeError leaking out of the storage layer."""


class ParentNotFoundError(ParentStoreError):
    """Raised when a `parent_id` has no file.

    Deliberately an error and not a None return. A missing parent means a
    child chunk in the vector store points at a section that is gone, and
    that is a broken citation -- PRD F-03 promises every answer names its
    source. Returning None would let a caller render an answer whose
    source text silently could not be loaded, which is the one failure a
    sourced-answer product cannot absorb. Loud beats plausible."""


class UnsafeIdentifierError(ParentStoreError):
    """Raised when a workspace id or parent id could not be used as a path
    segment. Both are generated by Sanad today, so this should never fire
    in normal use -- it is here because the day it does fire is the day
    something is placing attacker-controlled text into a file path."""


class CorruptParentError(ParentStoreError):
    """Raised when a parent file exists but cannot be trusted: unreadable
    JSON, a missing required field, or an `id` inside that disagrees with
    the file name it was loaded from."""


def _check_identifier(value: str, kind: str) -> str:
    if not value or not _SAFE_IDENTIFIER.match(value):
        raise UnsafeIdentifierError(
            f"{kind} is not usable as a path segment: {value!r}. Expected "
            f"letters, digits, hyphen or underscore only."
        )
    return value


def _base_dir(base_path: str | Path | None) -> Path:
    return Path(base_path if base_path is not None else get_settings().parent_store_path)


def _workspace_dir(workspace_id: str, base_path: str | Path | None) -> Path:
    """One directory per workspace, which is what makes isolation a
    property of the filesystem rather than of a filter somebody has to
    remember to apply (PRD F-01: an HR question never reaches the manuals).
    A read for the wrong workspace does not return the wrong parent -- it
    looks in a directory that does not contain it."""
    return _base_dir(base_path) / _check_identifier(workspace_id, "workspace_id")


def _parent_path(workspace_id: str, parent_id: str, base_path: str | Path | None) -> Path:
    directory = _workspace_dir(workspace_id, base_path)
    return directory / f"{_check_identifier(parent_id, 'parent_id')}{_JSON_SUFFIX}"


def save_parents(
    *,
    workspace_id: str,
    parents: list[Parent],
    base_path: str | Path | None = None,
) -> int:
    """Write every parent, returning how many were written.

    Each file is written to a temporary name and then moved into place
    with `os.replace`, which is atomic on both Windows and POSIX. The
    reason is not tidiness: parents are read at ANSWER time, while a sync
    may be writing them, so a plain write leaves a window where a reader
    can open a file that is half a JSON document. The move means a reader
    sees either the old complete file or the new complete file, never a
    torn one.

    Re-saving an existing parent id overwrites it, which is exactly what
    ST-14's derived ids were built for: re-ingesting a changed document
    lands on the same file names and replaces them in place instead of
    leaving the old ones behind."""
    directory = _workspace_dir(workspace_id, base_path)
    directory.mkdir(parents=True, exist_ok=True)

    for parent in parents:
        path = _parent_path(workspace_id, parent.id, base_path)
        payload = {
            _FIELD_ID: parent.id,
            _FIELD_TEXT: parent.text,
            _FIELD_SOURCE_FILE: parent.source_file,
            _FIELD_SECTION_LABEL: parent.section_label,
        }
        temporary = path.with_suffix(path.suffix + _TEMP_SUFFIX)
        # ensure_ascii=False so French and Arabic text stays readable in the
        # file itself; a store nobody can inspect by eye is a store nobody
        # can debug.
        temporary.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        os.replace(temporary, path)
    return len(parents)


def get_parent(
    *,
    workspace_id: str,
    parent_id: str,
    base_path: str | Path | None = None,
) -> Parent:
    """Load one parent, or raise.

    Verifies that the `id` recorded INSIDE the file matches the file it was
    loaded from. That guards the case a filename alone cannot: a file
    copied, renamed or restored from the wrong workspace's backup would
    otherwise be served as a section it is not, and the answer would cite
    the wrong source with complete confidence."""
    path = _parent_path(workspace_id, parent_id, base_path)
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ParentNotFoundError(
            f"no stored parent {parent_id!r} in workspace {workspace_id!r}. "
            f"Its chunk may have been indexed before the parent was written, "
            f"or the workspace may need a re-sync."
        ) from exc
    except OSError as exc:
        raise CorruptParentError(
            f"could not read parent {parent_id!r}: {exc.strerror or exc}"
        ) from exc

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise CorruptParentError(
            f"parent {parent_id!r} is not readable JSON: {exc}"
        ) from exc
    if not isinstance(payload, dict):
        raise CorruptParentError(f"parent {parent_id!r} is not a JSON object")

    missing = [
        field
        for field in (_FIELD_ID, _FIELD_TEXT, _FIELD_SOURCE_FILE)
        if field not in payload
    ]
    if missing:
        raise CorruptParentError(
            f"parent {parent_id!r} is missing required field(s): {', '.join(missing)}"
        )
    if payload[_FIELD_ID] != parent_id:
        raise CorruptParentError(
            f"parent file {path.name} contains id {payload[_FIELD_ID]!r}; the file "
            f"has been renamed, copied from another workspace, or restored over"
        )

    return Parent(
        id=payload[_FIELD_ID],
        text=payload[_FIELD_TEXT],
        source_file=payload[_FIELD_SOURCE_FILE],
        # Absent is treated as None (no heading), which is a legal value,
        # not a corruption: `.get` rather than `[...]` on purpose.
        section_label=payload.get(_FIELD_SECTION_LABEL),
    )


@dataclass(frozen=True)
class ParentListing:
    """Which parents in a workspace came from one source file.

    `unreadable` carries the file names that could not be inspected, and it
    is a separate field rather than an exception for the reason ST-12
    settled on the identical shape (`ScanResult.unreadable`): the only
    caller is deletion, deletion is what you run to reach a known end
    state, and one damaged file must not be able to block the cleanup of
    the other nine hundred. It must also not vanish silently, or the store
    accumulates litter nobody can see."""

    ids: list[str]
    unreadable: list[str]


def list_parent_ids(
    *,
    workspace_id: str,
    source_file: str,
    base_path: str | Path | None = None,
) -> ParentListing:
    """Every stored parent id in this workspace that came from `source_file`.

    Reads the `source_file` recorded INSIDE each file rather than deriving
    ids from `chunking._parent_id`. Deriving would be cheaper -- ids are
    `uuid5(source_file, index)`, so a caller could walk index 0 upward --
    but it would be a guess dressed as arithmetic: it has to stop somewhere,
    and one file missing from the middle of the run (a crash between two
    writes) silently truncates the sweep and strands every parent after it.
    What is on disk is the authority for what is on disk.

    The cost is one read per parent in the WORKSPACE, not per parent in the
    document, which is why this is a deletion-path function and not
    something an answer ever calls."""
    directory = _workspace_dir(workspace_id, base_path)
    if not directory.is_dir():
        return ParentListing(ids=[], unreadable=[])

    ids: list[str] = []
    unreadable: list[str] = []
    for path in sorted(directory.glob(f"*{_JSON_SUFFIX}")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
            stored_source = payload[_FIELD_SOURCE_FILE]
            stored_id = payload[_FIELD_ID]
        except (OSError, json.JSONDecodeError, KeyError, TypeError):
            unreadable.append(path.name)
            continue
        if stored_source == source_file:
            ids.append(stored_id)
    return ParentListing(ids=ids, unreadable=unreadable)


def delete_parents(
    *,
    workspace_id: str,
    parent_ids: list[str],
    base_path: str | Path | None = None,
) -> int:
    """Delete named parents, returning how many files actually went.

    Missing ids are not an error. Deletion is what a caller runs to reach a
    known end state, and it is re-run after partial failures and crashes,
    so "already gone" is success -- raising would make the safe thing to do
    (run it again) the thing that fails."""
    removed = 0
    for parent_id in parent_ids:
        path = _parent_path(workspace_id, parent_id, base_path)
        try:
            path.unlink()
        except FileNotFoundError:
            continue
        except OSError as exc:
            raise ParentStoreError(
                f"could not delete parent {parent_id!r}: {exc.strerror or exc}"
            ) from exc
        removed += 1
    return removed


def delete_workspace_parents(
    *, workspace_id: str, base_path: str | Path | None = None
) -> int:
    """Remove every parent file for a workspace, returning the count.

    PRD F-01 promises that deleting a workspace removes its derived data
    while leaving the user's source files untouched. The registry half of
    that already works (db/schema.sql cascades), but parents live on DISK,
    outside the database, so nothing in `workspaces.delete_workspace`
    reaches them -- it opens a SQL transaction and nothing else.

    Call `vector_store.delete_workspace` rather than this function
    directly: it drops the Qdrant collection and then calls this, so both
    derived stores go as one unit. A workspace delete that clears the
    parents but not the collection is not better than one that clears
    neither -- it just moves which half of the pair dangles.

    STILL NOT WIRED to `workspaces.delete_workspace`, which deletes
    registry rows and nothing on disk. That wiring is ST-17's, because it
    is ST-17 that owns a Qdrant client; opening a second one here would
    trip the single-client rule (ADR-04). Tracked in BUILD-STATE."""
    directory = _workspace_dir(workspace_id, base_path)
    if not directory.is_dir():
        return 0
    removed = 0
    for path in directory.glob(f"*{_JSON_SUFFIX}"):
        path.unlink()
        removed += 1
    directory.rmdir()
    return removed
