-- Sanad SQLite registry schema.
--
-- Translated from the PostgreSQL reference DDL in
-- docs/phase2/Sanad_Architecture_v1.0.md section 7.3, per the SQLite
-- deviation table in section 7.4:
--   uuid + gen_random_uuid()  -> TEXT, UUID generated by the application
--   timestamptz + now()       -> TEXT, ISO-8601 UTC, set by the application
--   boolean                   -> INTEGER 0/1
--   numeric(4,3)              -> REAL
--   CHECK (... IN ...)        -> unchanged
--   REFERENCES ... ON DELETE  -> unchanged; requires `PRAGMA foreign_keys = ON`
--                                on every connection (enforced in db/repo.py)
--                                for CASCADE / SET NULL to actually fire.
--
-- Deleting a workspace cascades to every derived row by design (PRD F-01:
-- derived data removed, source files on disk untouched). Running any
-- destructive statement (DROP, DELETE, TRUNCATE) against real data:
-- REQUIRES-HUMAN-AUTHORIZATION.

CREATE TABLE IF NOT EXISTS workspace (
  id             TEXT    PRIMARY KEY,
  name           TEXT    NOT NULL UNIQUE,
  folder_path    TEXT    NOT NULL,
  legal_flag     INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS document (
  id             TEXT    PRIMARY KEY,
  workspace_id   TEXT    NOT NULL REFERENCES workspace(id) ON DELETE CASCADE,
  file_name      TEXT    NOT NULL,
  file_type      TEXT    NOT NULL,
  content_hash   TEXT    NOT NULL,
  page_count     INTEGER,
  status         TEXT    NOT NULL CHECK (status IN ('active', 'failed', 'skipped', 'removed')),
  last_synced_at TEXT,
  UNIQUE (workspace_id, file_name)
);

CREATE TABLE IF NOT EXISTS sync_run (
  id             TEXT    PRIMARY KEY,
  workspace_id   TEXT    NOT NULL REFERENCES workspace(id) ON DELETE CASCADE,
  started_at     TEXT    NOT NULL,
  finished_at    TEXT,
  added          INTEGER NOT NULL DEFAULT 0,
  changed        INTEGER NOT NULL DEFAULT 0,
  unchanged      INTEGER NOT NULL DEFAULT 0,
  failed         INTEGER NOT NULL DEFAULT 0,
  removed        INTEGER NOT NULL DEFAULT 0,
  skipped        INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sync_item (
  id             TEXT    PRIMARY KEY,
  sync_run_id    TEXT    NOT NULL REFERENCES sync_run(id) ON DELETE CASCADE,
  document_id    TEXT    REFERENCES document(id) ON DELETE SET NULL,
  file_name      TEXT    NOT NULL,
  result         TEXT    NOT NULL CHECK (
                   result IN ('added', 'changed', 'unchanged', 'failed', 'removed', 'skipped')
                 ),
  reason         TEXT
);

CREATE TABLE IF NOT EXISTS eval_run (
  id                       TEXT    PRIMARY KEY,
  workspace_id             TEXT    NOT NULL REFERENCES workspace(id) ON DELETE CASCADE,
  run_at                   TEXT    NOT NULL,
  status                   TEXT    NOT NULL DEFAULT 'completed' CHECK (
                                      status IN ('running', 'completed', 'partial')
                                    ),
  question_total           INTEGER NOT NULL DEFAULT 0,
  groundedness             REAL,
  relevancy                REAL,
  refusal_pass             INTEGER NOT NULL DEFAULT 0,
  refusal_total            INTEGER NOT NULL DEFAULT 0,
  passed                   INTEGER NOT NULL DEFAULT 0,
  report_path              TEXT,
  failed_question_number   INTEGER,
  failed_question_id       TEXT,
  error                    TEXT
);

CREATE TABLE IF NOT EXISTS eval_result (
  id               TEXT    PRIMARY KEY,
  eval_run_id      TEXT    NOT NULL REFERENCES eval_run(id) ON DELETE CASCADE,
  question_id      TEXT    NOT NULL,
  kind             TEXT    NOT NULL CHECK (kind IN ('in_scope', 'out_of_scope')),
  groundedness     REAL,
  relevancy        REAL,
  passed           INTEGER NOT NULL,
  answer_kind      TEXT,
  answer_text      TEXT,
  sources_present  INTEGER,
  error            TEXT
);

-- F-15 (V2, Low). One row per answer a user has reacted to, keyed by
-- `answer_key` (ui/conversation.py's `Message.id`, a uuid4 stamped when
-- the message is built -- see that field for why it exists). `question`
-- and `answer_text` are copied in at write time rather than joined from
-- anywhere, because the in-memory Conversation they came from does not
-- survive a restart (PRD section 6, single user on one machine): the
-- feedback row is the only durable record of what was actually asked and
-- answered. UNIQUE (answer_key) is the idempotency guarantee
-- ui/feedback.py relies on -- giving feedback on the same answer twice is
-- an UPSERT (INSERT ... ON CONFLICT(answer_key) DO UPDATE) onto this
-- constraint, never a second row.
CREATE TABLE IF NOT EXISTS answer_feedback (
  id             TEXT    PRIMARY KEY,
  workspace_id   TEXT    NOT NULL REFERENCES workspace(id) ON DELETE CASCADE,
  answer_key     TEXT    NOT NULL UNIQUE,
  question       TEXT    NOT NULL,
  answer_text    TEXT    NOT NULL,
  verdict        TEXT    NOT NULL CHECK (verdict IN ('up', 'down')),
  comment        TEXT,
  created_at     TEXT    NOT NULL,
  updated_at     TEXT    NOT NULL
);
